<?php
/**
 * Implement hook_help() to display a small help message
 * if somebody clicks the "Help" link on the modules list.
 */
function qrauth_help( $path, $arg )
{
    switch ( $path )
    {
        case 'qrauth':
            // Help text for the simple page registered for this path.
            return( '<p>' . t('This module allows users who login with e-mail addresses to authenticate off an external system.') . '</p>' );
        case 'admin/help#qrauth':
            return( '<p>' . t('This module allows users who login with e-mail addresses to authenticate off an external system.') . '</p>' );
    }
}



/**
 * Implement hook_form_alter() to change the behaviour of the login form.
 *
 * Login validators are set in the user_login_default_validators() function in user.module.
 * They are normally set to array('user_login_name_validate',
 * 'user_login_authenticate_validate', 'user_login_final_validate').
 * We simply replace 'user_login_authenticate_validate' with 'extauth_login_validate'.
 */

function qrauth_form_alter(&$form, $form_state, $form_id)
{
  if ($form_id == 'user_login_block' || $form_id == 'user_login') {
    unset($form['links']);
    $form['#validate'] = array( 'user_login_name_validate', 'qrauth_login_validate', 'user_login_final_validate' );
    $form['qrcode'] = array('#type' => 'hidden', '#value' => generateQrCode());
  }
}

/**
 * The extauth_login_validate() function attempts to authenticate a user off the external system
 * using their e-mail address.
 */
function qrauth_login_validate( $form, &$form_state )
{
    global $user;

    $qrcode = $form_state['values']['qrcode'];
    unset($form_state['values']['qrcode']);

    if ( $qrcode ) {
        $uid = db_select('qrauth_qrcode', 'qr')
            ->condition('qrcode', $qrcode)
            ->fields('uid')
            ->execute()
            ->fetchField('uid');
        if ($uid) {
            // Log user in.
            $form_state['uid'] = $uid;
            user_login_submit(array(), $form_state);
        } // else drop through to the end and return nothing - Drupal will handle the rejection
    }
    else {
        // No qrcode passed, so use standard Drupal authentication function
        user_login_authenticate_validate( $form, $form_state );
    }
}


/**
 * The extauth_login_validate() function attempts to authenticate a user off the external system
 * using their e-mail address.
 */
function generateQrCode( )
{
    $qrcode = base64_encode(drupal_random_bytes(16));
    db_insert('qrauth_qrcode')
        ->fields(array(
            'qrcode' => $qrcode,
            'uid' => 0,
            'deadline' => REQUEST_TIME + 5 * 60,
        ))
        ->execute();
    return $qrcode;
}


/**
 * Implements hook_permission().
 *
 * Since the access to our new custom pages will be granted based on
 * special permissions, we need to define what those permissions are here.
 * This ensures that they are available to enable on the user role
 * administration pages.
 */
function qrauth_permission() {
  return array(
    'access arguments page' => array(
      'title' => t('Access page with arguments'),
      'description' => t('Allow users to access page with arguments'),
    ),
  );
}

/**
 * Constructs a descriptive page.
 *
 * Our menu maps this function to the path 'examples/page_example'.
 */
function qrauth_description() {
  return array(
    '#markup' =>
    t('<p>The page_example provides two pages, "simple" and "arguments".</p><p>The <a href="@simple_link">simple page</a> just returns a renderable array for display.</p><p>The <a href="@arguments_link">arguments page</a> takes two arguments and displays them, as in @arguments_link</p>',
      array(
        '@arguments_link' => url('examples/page_example/arguments/23/56', array('absolute' => TRUE)),
      )
    ),
  );
}

/**
 * A more complex page callback that takes arguments.
 *
 * This callback is mapped to the path 'examples/page_example/arguments/%/%'.
 *
 * The % arguments are passed in from the page URL. In our hook_menu
 * implementation we instructed the menu system to extract the last two
 * parameters of the path and pass them to this function as arguments.
 *
 * This function also demonstrates a more complex render array in the returned
 * values. Instead of just rendering the HTML with a theme('item_list'), the
 * list is left unrendered, and a #theme attached to it so that it can be
 * rendered as late as possible, giving more parts of the system a chance to
 * change it if necessary.
 *
 * Consult @link http://drupal.org/node/930760 Render Arrays documentation
 * @endlink for details.
 */
function qrauth_arguments($first) {
  // Make sure you don't trust the URL to be safe! Always check for exploits.
  if (!is_numeric($first)) {
    // We will just show a standard "access denied" page in this case.
    drupal_access_denied();
    // We actually don't get here.
    return;
  }

  $list[] = t("First number was @number.", array('@number' => $first));

  $render_array['qrauth_arguments'] = array(
    // The theme function to apply to the #items.
    '#theme' => 'item_list',
    // The list itself.
    '#items' => array("hallo"),
    '#title' => t('Argument Information'),
  );
  return $render_array;
}

/**
 * Implements hook_menu().
 *
 * Because hook_menu() registers URL paths for items defined by the function, it
 * is necessary for modules that create pages. Each item can also specify a
 * callback function for a given URL. The menu items returned here provide this
 * information to the menu system.
 *
 * We will define some menus, and their paths will be interpreted as follows:
 *
 * If the user accesses http://example.com/?q=examples/page_example/simple,
 * the menu system will first look for a menu item with that path. In this case
 * it will find a match, and execute page_example_simple().
 *
 * If the user accesses http://example.com/?q=examples/page_example/arguments,
 * the menu system will find no explicit match, and will fall back to the
 * closest match, 'examples/page_example', executing page_example_description().
 *
 * If the user accesses
 * http://example.com/?q=examples/page_example/arguments/1/2, the menu
 * system will first look for examples/page_example/arguments/1/2. Not finding
 * a match, it will look for examples/page_example/arguments/1/%. Again not
 * finding a match, it will look for examples/page_example/arguments/%/2.
 * Yet again not finding a match, it will look for
 * examples/page_example/arguments/%/%. This time it finds a match, and so will
 * execute page_example_arguments(1, 2). Since the parameters are passed to
 * the function after the match, the function can do additional checking or
 * make use of them before executing the callback function.
 *
 * @see hook_menu()
 * @see menu_example
 */
function qrauth_menu() {
  // This is the minimum information you can provide for a menu item. This menu
  // item will be created in the default menu, usually Navigation.
  $items['qrauth'] = array(
    'title' => 'Page Example',
    'page callback' => 'qrauth_description',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  // By using the MENU_CALLBACK type, we can register the callback for this
  // path without the item appearing in the menu; the admin cannot enable the
  // item in the menu, either.
  //
  // Notice that 'page arguments' is an array of numbers. These will be
  // replaced with the corresponding parts of the menu path. In this case a 0
  // would be replaced by 'example', a 1 by 'page_example', and a 2 by
  // 'arguments.' 3 and 4 will be replaced by whatever the user provides.
  // These will be passed as arguments to the page_example_arguments() function.
  $items['qrauth/%'] = array(
    'page callback' => 'qrauth_arguments',
    'page arguments' => array(1),
    'access arguments' => array('access arguments page'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}