/**
 * Implement hook_help() to display a small help message
 * if somebody clicks the "Help" link on the modules list.
 */
function qrauth_help( $path, $arg )
{
    switch ( $path )
    {
        case 'admin/help#extauth':
        {
            return( '<p>' . t('This module allows users who login with e-mail addresses to authenticate off an external system.') . '</p>' );
        }
    }
}

/**
 * Implement hook_form_alter() to change the behaviour of the login form.
 *
 * Login validators are set in the user_login_default_validators() function in user.module.
 * They are normally set to array('user_login_name_validate',
 * 'user_login_authenticate_validate', 'user_login_final_validate').
 * We simply replace 'user_login_authenticate_validate' with 'extauth_login_validate'.
 */
function qrauth_form_user_login_alter( &$form, $form_state )
{
    unset($form['links']);
    $form['#validate'] = array( 'user_login_name_validate', 'qrauth_login_validate', 'user_login_final_validate' );
    $form['qrcode'] = array('#type' => 'hidden', '#value' => generateQrCode());
}

function qrauth_form_user_login_block_alter( &$form, $form_state )
{
    return qrauth_form_user_login_alter( $form, $form_state );
}

/**
 * The extauth_login_validate() function attempts to authenticate a user off the external system
 * using their e-mail address.
 */
function qrauth_login_validate( $form, &$form_state )
{
    global $user;

    $qrcode = $form_state['values']['qrcode'];
    unset($form_state['values']['qrcode']);

    if ( $qrcode ) {
        $uid = db_select('qrcode', 'qr')
            ->condition('qr', $qrcode)
            ->fields('uid');
            ->execute()
            ->fetchField('uid');
        if ($uid) {
            // Log user in.
            form_state['uid'] = $uid;
            ser_login_submit(array(), $form_state);
        } // else drop through to the end and return nothing - Drupal will handle the rejection
    }
    else {
        // No qrcode passed, so use standard Drupal authentication function
        user_login_authenticate_validate( $form, $form_state );
    }
}


/**
 * The extauth_login_validate() function attempts to authenticate a user off the external system
 * using their e-mail address.
 */
function generateQrCode( )
{
    $qrcode = substr(base64(mt_rand()), 0, 15);
    return $qrcode;
}
